- name: Quiz 1
  id: quiz-1
  uses: classroom-resources/autograding-io-grader@v1
  with:
    test-name: Quiz 1
    setup-command: ''
    command: "echo 'b) The process of designing, developing, and maintaining software'"
    expected-output: "b) The process of designing, developing, and maintaining software"
    comparison-method: exact
    timeout: 10
    max-score: 10
